### PR TITLE
Updated nerdfont icons

### PR DESCRIPTION
**Pull request by david-0609**
The nerd font icons you are using are deprecated, making them not render properly on the newer versions. I have updated the icons for you here.

### CODE REVIEW

**Comment by justinhj** [comment]
Thanks for your contribution. I wasn't able to test the fix. I assumed I could simply download the latest Nerd font and it would break my code but it did not. I also downloaded another font to test that and also no problem. Could you give a link to the font you are using so I can verify?
I am thinking that this will break for others using the older font once it is merged so I may need to add a configuration option.

**Comment by david-0609** [comment]
I am using Jetbrains Mono Nerd Font version [3.1.1](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip)
As you see in the image, the icon isn't rendering properly because the icon is deprecated in version 3.x of nerd fonts
Screenshot_20240114_182749

**Comment by david-0609** [comment]
The changelog for version 3.0.0 on the nerd font website also announced that some icons will be removed. They no longer exist in newer versions of Nerd Font and [this tool](https://github.com/loichyan/nerdfix) can update the old icons to the new ones

**Comment by justinhj** [comment]
Thank you for the additional resources. I will merge and do a new release with some documentation in case old font users run into issues.

**Pull request merged**
